[dark]
[colors]
scheme_name = Dorakura-Kyoto
scheme_author = GrandBirdLizard

base00 = 151620
base01 = 212731
base02 = 3e3f51
base03 = 797881
base04 = 8e8e90
base05 = b6b6b8
base06 = cacacc
base07 = dcdcde
base08 = ff757f
base09 = ffb86c
base0A = f1fa8c
base0B = 9ece6a
base0C = 73daca
base0D = aa81e4
base0E = bd93f9
base0F = c49efa


;Copyright (c) 2026, GrandBIRDLizard.
;BSD 3-Clause, All rights reserved.

;Redistribution and use in source and binary forms, with or without
;modification, are permitted provided that the following conditions are met:

;1. Redistributions of source code must retain the above copyright notice,
;   this list of conditions and the following disclaimer.

;2. Redistributions in binary form must reproduce the above copyright notice,
;   this list of conditions and the following disclaimer in the documentation
;   and/or other materials provided with the distribution.

;3. Neither the name of Your Name nor the names of its contributors may be used
;   to endorse or promote products derived from this software without specific
;   prior written permission.

;THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
;DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
;FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
;DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
;SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
;CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
;OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
;OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
